#!/bin/bash
python latest_game_ordinary_overage.py
python latest_game_ordinary_betting.py
python latest_game_ordinary_betting_short.py
python latest_game_ordinary_store.py
python latest_game_ordinary_pkrecord.py
